version: "3.3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        uvicorn main:app
