version: "3"
services:
  app:
    image: 909232941556.dkr.ecr.ap-northeast-2.amazonaws.com/my-infra-pixhelves-app-test
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file: 
      - .env
    depends_on: 
      - db

  db:
    image: mongo:4.2.14
    

  web:
    image: 909232941556.dkr.ecr.ap-northeast-2.amazonaws.com/stickit-ecs-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80
