name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MONGODB_URL: ${{ secrets.MONGODB_URL }}
          envkey_MONGODB_TEST_URL: ${{ secrets.MONGODB_TEST_URL }}
          envkey_SERVER_NAME: "127.0.0.1"
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      - name: Start MongoDB
        if: ${{ !env.ACT }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
        env:
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        run: |
          docker exec -it mongodb mongo --eval "use pixhelves_test_db; db.createUser({user: "root", pwd: "$MONGO_DB_PASSWORD", roles:["readWrite", "userAdmin"]});"
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install
      - name: Lint with flake8
        run: |
          source $HOME/.poetry/env
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        run: |
          source $HOME/.poetry/env
          poetry run pytest
