name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Start MongoDB
        if: ${{ !env.ACT }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install
      - name: Lint with flake8
        run: |
          source $HOME/.poetry/env
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        run: |
          source $HOME/.poetry/env
          touch .env
          echo MONGODB_URL=${{ secrets.MONGODB_URL }} >> .env
          echo MONGODB_TEST_URL=${{ secrets.MONGODB_TEST_URL }} >> .env
          echo SERVER_NAME=127.0.0.1 >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          poetry run pytest
